name: skeleton_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1
  intl_translation: 0.17.10+1
  flutter_hooks: 0.14.1
  dartkt: 1.0.4
  json_serializable: 3.5.0
  flutter_bloc: 6.0.6
  hydrated_bloc: 6.0.2
  equatable: 1.2.4
  dio: 3.0.10
  provider: 4.3.2+2
  flutter_provider: 1.1.1
  # flutter_platform_widgets:
  #   git:
  #     url: git@github.com:stryder-dev/flutter_platform_widgets.git
  #     ref: master
  flutter_platform_widgets: 0.70.1
  shared_preferences: 0.5.12
  firebase_auth: 0.18.1+2
  firebase_auth_web: 0.3.1+1
  firebase_core_web: 0.2.0
  webview_flutter: 1.0.0
  google_sign_in: 4.5.4
  flutter_facebook_login: 3.0.0
  loading: 1.0.2
  table_calendar: 2.2.3
  sliding_up_panel: 1.0.2
  swipe_stack: 1.0.0
  flutter_swiper: 1.1.6
  calendar_strip: 1.0.6
  url_launcher: 5.7.2
  #  flutter_nfc_kit:
  pedantic: 1.9.2
  usage: 3.4.2
  path_provider: 1.6.18
  sentry: 3.0.1
  flutter_keyboard_visibility: 3.2.2
  curved_navigation_bar: 0.3.4
  persistent_bottom_nav_bar: 2.1.0
  pdf: 1.11.2
  flutter_full_pdf_viewer: 1.0.6
  sticky_headers: 0.1.8+1
  planner: 0.1.0
  flutter_svg: 0.18.1
  calendar_views: 0.5.2
  rxdart: 0.24.1
  line_awesome_flutter: 1.0.1
  animated_theme_switcher: 1.0.7
  flutter_screenutil: 3.1.1
  flutter_tindercard: 0.2.0
  share: 0.6.5+2
  scrollable_positioned_list: 0.1.7
  image_picker: 0.6.7+12







  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.3

  #dependency_overrides:
  # analyzer: '0.39.14'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  build_version: 2.0.1
  effective_dart: ^1.0.0
  supercharged: 1.10.0
  simple_animations: 2.2.2


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
